services:
  # ✅ FRONTEND
  frontend:
    build:
      context: .
      dockerfile: magic-casino-front/Dockerfile
    container_name: frontend
    image: magic-casino-frontend:prod
    expose:
      - "80"
    restart: always
    depends_on:
      - core

  # ✅ REDIS
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
  
 # 🐰 RABBITMQ (NOVO SERVIÇO DE FILAS)
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbit
    ports:
      - "5672:5672"   # Porta de comunicação (AMQP)
      - "15672:15672" # Painel de Gestão (http://localhost:15672)
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    # 👇 O SEGREDO PARA NÃO DAR ERRO NO CORE 👇
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ✅ CORE (Backend Principal)
  core:
    build:
      context: .
      dockerfile: Magic-casino/Dockerfile
    image: magic-casino-core:prod
    container_name: core
    
    # Adicione esta linha para garantir que o Docker leia o arquivo .env
    env_file:
      - .env

    environment:
      # Banco de Dados e Cache
      ConnectionStrings__Redis: "redis:6379"
      ConnectionStrings__DefaultConnection: "${DB_CONN_CORE}"
      
      # JWT e Segurança
      Jwt__Key: "${JWT_SECRET}"
      Jwt__Issuer: "${JWT_ISSUER}"
      Jwt__Audience: "${JWT_AUDIENCE}"
      
      # APIs Externas
      VELANA_API_KEY: "${VELANA_API_KEY}"
      MY_API_URL: "${MY_API_URL}"
      
      # RabbitMQ
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "admin"
      RABBITMQ_PASS: "admin"

      # CONFIGURAÇÕES DE E-MAIL (SMTP)
      SmtpSettings__Host: "smtpout.secureserver.net"
      SmtpSettings__Port: "587"
      SmtpSettings__User: "contato@quebrandoabanca.bet"
      SmtpSettings__Password: "${SMTP_PASSWORD}" 

    expose:
      - "8080"
    restart: always
    depends_on:
      - redis
      - rabbitmq

  # ✅ SPORTBOOK
  sportbook:
    build:
      context: .
      dockerfile: Magic-casino-sportbook/Dockerfile
    image: magic-casino-sportbook:prod
    container_name: sportbook
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      REDIS_CONNECTION_STRING: "redis:6379,abortConnect=false"
      ConnectionStrings__Redis: "redis:6379"
      ConnectionStrings__DefaultConnection: "${DB_CONN_SPORTBOOK}"
      OddsApiKey: "${ODDS_API_KEY}"
      Jwt__Key: "${JWT_SECRET}"
      Jwt__Issuer: "${JWT_ISSUER}"
      Jwt__Audience: "${JWT_AUDIENCE}"
      ODDS_PROVIDER: "${ODDS_PROVIDER}"
      BETSAPI_TOKEN: "${BETSAPI_TOKEN}"
    expose:
      - "8080"
    restart: always
    depends_on:
      - redis

  # ✅ SLOT
  slot:
    build:
      context: .
      dockerfile: Magic-casino-slot/Dockerfile
    image: magic-casino-slot:prod
    container_name: slot
    environment:
      ConnectionStrings__Redis: "redis:6379"
      ConnectionStrings__DefaultConnection: "${DB_CONN_SLOT}"
      Jwt__Key: "${JWT_SECRET}"
      Jwt__Issuer: "${JWT_ISSUER}"
      Jwt__Audience: "${JWT_AUDIENCE}"
    expose:
      - "8080"
    restart: always
    depends_on:
      - redis


# 🏆 TOURNAMENT (Novo Serviço)
  tournament:
    build:
      context: .
      dockerfile: Magic-casino-tournament/Dockerfile
    image: magic-casino-tournament:prod
    container_name: tournament
    environment:
      # Banco de dados (Você precisará criar essa variável no .env)
      ConnectionStrings__DefaultConnection: "${DB_CONN_TOURNAMENT}"
      
      # Redis e RabbitMQ (Comunicação)
      ConnectionStrings__Redis: "redis:6379"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "admin"
      RABBITMQ_PASS: "admin"
      
      # Autenticação (Mesmas chaves dos outros)
      Jwt__Key: "${JWT_SECRET}"
      Jwt__Issuer: "${JWT_ISSUER}"
      Jwt__Audience: "${JWT_AUDIENCE}"
    expose:
      - "8080"
    restart: always
    depends_on:
      - redis
      - rabbitmq
      - core

    # 🚦 GATEWAY (NGINX)
  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8888:8888"
    depends_on:
      - frontend
      - sportbook
      - core
      - slot
    restart: always

# Volumes persistentes
volumes:
  rabbitmq_data: