services:
  # ✅ FRONTEND VUE.JS
  frontend:
    build:
      context: .
      dockerfile: magic-casino-front/Dockerfile
    container_name: frontend
    image: magic-casino-frontend:dev
    ports:
      - "80:80" # ✅ Mapeia o tráfego do domínio quebrandoabanca.bet
    restart: always
    depends_on:
      - core

  # SERVIÇO CORE
  core:
    build:
      context: .
      dockerfile: Magic-casino/Dockerfile
    image: magic-casino-core:dev
    container_name: core
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=magic-casino-db.cl2e0cqa67wd.sa-east-1.rds.amazonaws.com;Port=5432;Database=magic_core;Username=postgres;Password=Rodr2108luca;Ssl Mode=Require;Trust Server Certificate=true
      - Jwt__Key=M@gic_C@sino_Secret_Key_2026_Security
      - Jwt__Issuer=MagicCasinoServer
      - Jwt__Audience=MagicCasinoApp
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: always

  # SERVIÇO SPORTBOOK
  sportbook:
    build:
      context: .
      dockerfile: Magic-casino-sportbook/Dockerfile
    image: magic-casino-sportbook:dev
    container_name: sportbook
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=magic-casino-db.cl2e0cqa67wd.sa-east-1.rds.amazonaws.com;Port=5432;Database=magic_sportbook;Username=postgres;Password=Rodr2108luca;Ssl Mode=Require;Trust Server Certificate=true
      - Jwt__Key=M@gic_C@sino_Secret_Key_2026_Security
      - Jwt__Issuer=MagicCasinoServer
      - Jwt__Audience=MagicCasinoApp
    ports:
      - "8090:8080"
      - "8091:8081"
    restart: always

  # SERVIÇO SLOT
  slot:
    build:
      context: .
      dockerfile: Magic-casino-slot/Dockerfile
    image: magic-casino-slot:dev
    container_name: slot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=magic-casino-db.cl2e0cqa67wd.sa-east-1.rds.amazonaws.com;Port=5432;Database=magic_slot;Username=postgres;Password=Rodr2108luca;Ssl Mode=Require;Trust Server Certificate=true
      - Jwt__Key=M@gic_C@sino_Secret_Key_2026_Security
      - Jwt__Issuer=MagicCasinoServer
      - Jwt__Audience=MagicCasinoApp
    ports:
      - "8100:8080"
      - "8101:8081"
    restart: always