worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            
            # 👇 O SEGREDO DO F5 NO VUE 👇
            try_files $uri $uri/ /index.html;
        }

        # Evita log de erro 404 para arquivos estáticos (opcional)
        location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
            root /usr/share/nginx/html;
            expires 1y;
            add_header Cache-Control "public, no-transform";
        }
    }
}