// <auto-generated />
using System;
using Magic_casino_sportbook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Magic_casino_sportbook.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108194256_EstruturaFinalMercados")]
    partial class EstruturaFinalMercados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Magic_casino_sportbook.Models.MarketOdd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutcomeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Point")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitMargin")
                        .HasColumnType("numeric");

                    b.Property<string>("SportsEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SportsEventId");

                    b.ToTable("MarketOdds");
                });

            modelBuilder.Entity("Magic_casino_sportbook.Models.SportsEvent", b =>
                {
                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CommenceTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SportKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExternalId");

                    b.ToTable("SportsEvents");
                });

            modelBuilder.Entity("Magic_casino_sportbook.Models.MarketOdd", b =>
                {
                    b.HasOne("Magic_casino_sportbook.Models.SportsEvent", null)
                        .WithMany("Odds")
                        .HasForeignKey("SportsEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Magic_casino_sportbook.Models.SportsEvent", b =>
                {
                    b.Navigation("Odds");
                });
#pragma warning restore 612, 618
        }
    }
}
