// <auto-generated />
using System;
using Magic_casino_sportbook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Magic_casino_sportbook.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108183224_CriarTabelaSports")]
    partial class CriarTabelaSports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Magic_casino_sportbook.Models.SportsEvent", b =>
                {
                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CommenceTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ProfitMargin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RawOddsAway")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RawOddsDraw")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RawOddsHome")
                        .HasColumnType("numeric");

                    b.Property<string>("SportKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExternalId");

                    b.ToTable("SportsEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
