// <auto-generated />
using System;
using Magic_casino.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Magic_casino.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108220134_AddNameColumn")]
    partial class AddNameColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Magic_casino.Data.User", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("AgentCode")
                        .HasColumnType("text")
                        .HasColumnName("agent_code");

                    b.Property<DateTime?>("AgentLinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("agent_linked_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Cpf");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Magic_casino.Data.Wallet", b =>
                {
                    b.Property<string>("UserCpf")
                        .HasColumnType("character varying(11)")
                        .HasColumnName("user_cpf");

                    b.Property<decimal>("BalanceBonus")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_bonus");

                    b.Property<decimal>("BalanceFiver")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_fiver");

                    b.Property<decimal>("BalanceQab")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_qab");

                    b.HasKey("UserCpf");

                    b.ToTable("wallets");
                });

            modelBuilder.Entity("Magic_casino.Data.Wallet", b =>
                {
                    b.HasOne("Magic_casino.Data.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Magic_casino.Data.Wallet", "UserCpf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Magic_casino.Data.User", b =>
                {
                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
